version: '3'

services:
  nginx:
    build:
      context: ./nginx
    container_name: nginx
    restart: always
    ports: 
      - '8080:80'
    depends_on:
      - app
    networks:
      - node-network

  app:
    build:
      context: ./node
    container_name: app
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s docker-entrypoint.sh
    command: "node index.js"
    volumes:
      - ./node:/usr/src/app
    tty: true
    networks:
      - node-network
    ports:
      - "3000:3000"
    depends_on:
      - db

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - node-network
    ports:
      - "3306:3306"
      
  
networks:
  node-network:
    driver: bridge